### ISSUE TITLE
MainNet Ready AutoNode Checklist

### ISSUE THREAD

**Issue by rhazberries** [harmony-one/auto-node#33]
### Minimum Required Features
- [x] MainNet `rclone` support (archival & state-pruned)
- [x] Support MainNet & TestNet endpoints
- [x] #30 Prompt user before deactivating validator
- [x] Remove hard-reset triggers for mainnet
- [x] #31 Remove requirement to have sudo access to run AutoNode
- [x] Formalize versioning & inform user of AutoNode releases
- [x] Enable install & updates through `./auto_node.sh`
- [x] Remove `shell=True` subprocess calls when possible
- [x] Improve passphrase security, invalidate stored passphrase after autnode is shutdown.
- [x] Add option to tune Kernal according to [this](https://github.com/harmony-one/harmony/blob/master/scripts/node.sh#L84-L151).
- [x] Confirm kill & deactivation of node if still elected
- [x] Confirm keys to remove when doing cleanse-bls 

### Testing & Review
- [ ] Final testing on MainNet
- [ ] Code review from @LeoHChen 
- [x] Design review from P-Ops
- [x] Documentation update
- [x] Usability testing with business team

**Comment by yelllowsin** [comment]
Great work, will test this once merged.

**Comment by yelllowsin** [comment]
Tested autonode and is working nicely, updated a few things on the docs today to make it easier for deployment on testnet. Also two other p-ops are running it on LRTN. 

Not sure if there is something pending on the list above, but i would consider it done and can be closed.
If we find issues i will open them on this repository.
